name: Verifier

on: [ pull_request ]

permissions:
  contents: read
  pull-requests: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources ğŸ“„
        uses: actions/checkout@v4

      - name: Set up JDK 24 â˜•
        uses: actions/setup-java@v4
        with:
          java-version: '24'
          distribution: 'temurin'

      - name: Grant execute permission for gradlew ğŸ’¾
        run: chmod +x gradlew

      - name: Run Spotless check ğŸ—ï¸
        run: ./gradlew :backend:spotlessCheck